Repository paw-ong/pawong-backend, pull requests merged in 2025-05, with the labels that each got.

#31 [PW-23] Adoption-Shelter port-adapter 구조 보호소정보 요청-반환
  src/main/java/kr/co/pawong/pwbe/adoption/application/domain/Adoption.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/domain/AdoptionCreate.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/domain/AdoptionUpdate.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/AdoptionQueryServiceImpl.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/ApiRequestService.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/port/AdoptionQueryRepository.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/port/ShelterInfoPort.java
  src/main/java/kr/co/pawong/pwbe/adoption/infrastructure/repository/AdoptionJpaRepository.java
  src/main/java/kr/co/pawong/pwbe/adoption/infrastructure/repository/AdoptionQueryRepositoryImpl.java
  src/main/java/kr/co/pawong/pwbe/adoption/infrastructure/repository/entity/AdoptionEntity.java
  src/main/java/kr/co/pawong/pwbe/adoption/presentation/controller/AdoptionUpdateController.java
  src/main/java/kr/co/pawong/pwbe/adoption/presentation/port/AdoptionQueryService.java
  src/main/java/kr/co/pawong/pwbe/shelter/application/service/ShelterQueryServiceImpl.java
  src/main/java/kr/co/pawong/pwbe/shelter/application/service/ShelterUpdateServiceImpl.java
  src/main/java/kr/co/pawong/pwbe/shelter/application/service/port/ShelterQueryRepository.java
  src/main/java/kr/co/pawong/pwbe/shelter/infrastructure/adapter/ShelterAdapter.java
  src/main/java/kr/co/pawong/pwbe/shelter/infrastructure/repository/ShelterJpaRepository.java
  src/main/java/kr/co/pawong/pwbe/shelter/infrastructure/repository/ShelterQueryRepositoryImpl.java
  src/main/java/kr/co/pawong/pwbe/shelter/infrastructure/repository/ShelterUpdateRepositoryImpl.java
  src/main/java/kr/co/pawong/pwbe/shelter/presentation/controller/ShelterUpdateController.java
  src/main/java/kr/co/pawong/pwbe/shelter/presentation/controller/dto/ShelterInfoDto.java
  src/main/java/kr/co/pawong/pwbe/shelter/presentation/port/ShelterQueryService.java
  src/main/java/kr/co/pawong/pwbe/shelter/presentation/port/ShelterUpdateService.java
Labels: 🔨 Refactor, ✨ Feature

#29 [PW-18] 공공데이터 저장, AI 정제, ES 저장
  infra/docker-compose/elasticsearch/config/elasticsearch.yml
  src/main/java/kr/co/pawong/pwbe/adoption/application/domain/Adoption.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/domain/AdoptionCreate.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/domain/AdoptionUpdate.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/AdoptionEsServiceImpl.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/AdoptionQueryServiceImpl.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/AdoptionSearchServiceImpl.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/AdoptionUpdateServiceImpl.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/ApiRequestService.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/ApiRequestServiceImpl.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/port/AdoptionEsRepository.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/port/AdoptionQueryRepository.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/port/AdoptionUpdateRepository.java
  src/main/java/kr/co/pawong/pwbe/adoption/enums/UpKindNm.java
  src/main/java/kr/co/pawong/pwbe/adoption/infrastructure/external/ai/enums/AnimalFeature.java
  src/main/java/kr/co/pawong/pwbe/adoption/infrastructure/external/ai/openai/OpenAiChatAdapter.java
  src/main/java/kr/co/pawong/pwbe/adoption/infrastructure/repository/AdoptionEsRepository.java
  src/main/java/kr/co/pawong/pwbe/adoption/infrastructure/repository/AdoptionEsRepositoryImpl.java
  src/main/java/kr/co/pawong/pwbe/adoption/infrastructure/repository/AdoptionJpaRepository.java
  src/main/java/kr/co/pawong/pwbe/adoption/infrastructure/repository/AdoptionQueryRepositoryImpl.java
  src/main/java/kr/co/pawong/pwbe/adoption/infrastructure/repository/AdoptionUpdateRepositoryImpl.java
  src/main/java/kr/co/pawong/pwbe/adoption/infrastructure/repository/document/AdoptionDocument.java
  src/main/java/kr/co/pawong/pwbe/adoption/infrastructure/repository/entity/AdoptionEntity.java
  src/main/java/kr/co/pawong/pwbe/adoption/presentation/controller/AdoptionUpdateController.java
  src/main/java/kr/co/pawong/pwbe/adoption/presentation/port/AdoptionEsService.java
  src/main/java/kr/co/pawong/pwbe/adoption/presentation/port/AdoptionQueryService.java
  src/main/java/kr/co/pawong/pwbe/adoption/presentation/port/AdoptionUpdateService.java
  src/main/java/kr/co/pawong/pwbe/adoption/presentation/port/ApiRequestService.java
  src/main/resources/application-dev.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 🔨 Refactor, ✨ Feature

#30 [PW-26] 자동완성 기능을 구현했습니다. 정말 간단하게 ES만 조회합니다.
  infra/docker-compose/elasticsearch/Dockerfile
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/AdoptionSearchServiceImpl.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/port/AdoptionSearchRepository.java
  src/main/java/kr/co/pawong/pwbe/adoption/infrastructure/repository/AdoptionSearchRepositoryImpl.java
  src/main/java/kr/co/pawong/pwbe/adoption/infrastructure/repository/document/AutocompleteDocument.java
  src/main/java/kr/co/pawong/pwbe/adoption/presentation/controller/AdoptionSearchController.java
  src/main/java/kr/co/pawong/pwbe/adoption/presentation/controller/dto/response/AdoptionAutocompleteResponse.java
  src/main/java/kr/co/pawong/pwbe/adoption/presentation/port/AdoptionSearchService.java
Labels: ✨ Feature

#33 [PW-25] 추천리스트 API 구현
  src/main/java/kr/co/pawong/pwbe/adoption/application/domain/Adoption.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/AdoptionEsServiceImpl.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/AdoptionQueryServiceImpl.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/AdoptionUpdateServiceImpl.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/port/AdoptionQueryRepository.java
  src/main/java/kr/co/pawong/pwbe/adoption/infrastructure/repository/AdoptionJpaRepository.java
  src/main/java/kr/co/pawong/pwbe/adoption/infrastructure/repository/AdoptionQueryRepositoryImpl.java
  src/main/java/kr/co/pawong/pwbe/adoption/infrastructure/repository/document/AdoptionDocument.java
  src/main/java/kr/co/pawong/pwbe/adoption/infrastructure/repository/entity/AdoptionEntity.java
  src/main/java/kr/co/pawong/pwbe/adoption/presentation/controller/AdoptionQueryController.java
  src/main/java/kr/co/pawong/pwbe/adoption/presentation/controller/AdoptionUpdateController.java
  src/main/java/kr/co/pawong/pwbe/adoption/presentation/controller/dto/response/AdoptionRecommendResponses.java
  src/main/java/kr/co/pawong/pwbe/adoption/presentation/port/AdoptionQueryService.java
  src/main/java/kr/co/pawong/pwbe/shelter/application/service/ShelterQueryServiceImpl.java
  src/main/java/kr/co/pawong/pwbe/shelter/infrastructure/adapter/ShelterAdapter.java
Labels: 🔨 Refactor, ✨ Feature

#32 [PW-28] 유기동물 검색 기능에 지역 조건 추가
  build.gradle
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/dto/request/AdoptionSearchCondition.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/support/AdoptionQueryBuilder.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/support/AdoptionSearchMapper.java
  src/main/java/kr/co/pawong/pwbe/adoption/infrastructure/repository/AdoptionSearchRepositoryImpl.java
  src/main/java/kr/co/pawong/pwbe/adoption/presentation/controller/dto/request/AdoptionSearchRequest.java
  src/test/java/kr/co/pawong/pwbe/adoption/application/service/support/AdoptionSearchMapperTest.java
  src/test/java/kr/co/pawong/pwbe/adoption/infrastructure/repository/AdoptionQueryBuilderTest.java
  src/test/java/kr/co/pawong/pwbe/adoption/infrastructure/repository/TestElasticsearchContainer.java
  src/test/java/kr/co/pawong/pwbe/adoption/infrastructure/repository/document/TestDocument.java
  testcontainers.properties
Labels: ✨ Feature

#37 [PW-36] AI 정제 메서드 리팩토링
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/AdoptionUpdateServiceImpl.java
  src/main/resources/application.yml
Labels: 🔨 Refactor

#35 [PW-34] 지역 정보 ES에 저장
  src/main/java/kr/co/pawong/pwbe/adoption/application/domain/Adoption.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/AdoptionAiServiceImpl.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/AdoptionEsServiceImpl.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/dto/request/AdoptionEsDto.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/dto/request/RegionInfoDto.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/port/AdoptionEsRepository.java
  src/main/java/kr/co/pawong/pwbe/adoption/infrastructure/repository/AdoptionEsRepositoryImpl.java
  src/main/java/kr/co/pawong/pwbe/adoption/infrastructure/repository/document/AdoptionDocument.java
  src/main/java/kr/co/pawong/pwbe/shelter/application/service/ShelterQueryServiceImpl.java
  src/main/resources/application-dev.yml
Labels: ✨ Feature

#43 [PW-42] @value 괄호 누락 수정
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/AdoptionEsServiceImpl.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/AdoptionUpdateServiceImpl.java
Labels: 🐞 BugFix

#41 [PW-27] 유기동물 찜 API 구현
  src/main/java/kr/co/pawong/pwbe/favorites/application/domain/Favorites.java
  src/main/java/kr/co/pawong/pwbe/favorites/application/service/FavoritesService.java
  src/main/java/kr/co/pawong/pwbe/favorites/application/service/FavoritesServiceImpl.java
  src/main/java/kr/co/pawong/pwbe/favorites/application/service/dto/FavoritesRequest.java
  src/main/java/kr/co/pawong/pwbe/favorites/application/service/port/FavoritesRepository.java
  src/main/java/kr/co/pawong/pwbe/favorites/infrastructure/entity/FavoritesEntity.java
  src/main/java/kr/co/pawong/pwbe/favorites/infrastructure/entity/repository/FavoritesJpaRepository.java
  src/main/java/kr/co/pawong/pwbe/favorites/infrastructure/entity/repository/FavoritesRepositoryImpl.java
  src/main/java/kr/co/pawong/pwbe/favorites/presentation/FavoritesController.java
  src/main/java/kr/co/pawong/pwbe/favorites/presentation/dto/response/FavoritesListResponse.java
  src/main/java/kr/co/pawong/pwbe/favorites/presentation/dto/response/FavoritesResponse.java
  src/main/java/kr/co/pawong/pwbe/user/application/domain/User.java
  src/main/java/kr/co/pawong/pwbe/user/application/service/AuthServiceImpl.java
  src/main/java/kr/co/pawong/pwbe/user/application/service/UserQueryServiceImpl.java
  src/main/java/kr/co/pawong/pwbe/user/application/service/port/UserQueryRepository.java
  src/main/java/kr/co/pawong/pwbe/user/config/SecurityConfig.java
  src/main/java/kr/co/pawong/pwbe/user/infrastructure/repository/UserQueryRepositoryImpl.java
  src/main/java/kr/co/pawong/pwbe/user/infrastructure/security/JwtTokenProvider.java
  src/main/java/kr/co/pawong/pwbe/user/infrastructure/security/filter/JwtFilter.java
Labels: ✨ Feature

#40 [PW-38] 상세보기 API 구현
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/AdoptionQueryServiceImpl.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/dto/response/AdoptionDetailDto.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/port/AdoptionQueryRepository.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/port/ShelterDetailPort.java
  src/main/java/kr/co/pawong/pwbe/adoption/infrastructure/repository/AdoptionJpaRepository.java
  src/main/java/kr/co/pawong/pwbe/adoption/infrastructure/repository/AdoptionQueryRepositoryImpl.java
  src/main/java/kr/co/pawong/pwbe/adoption/presentation/controller/AdoptionQueryController.java
  src/main/java/kr/co/pawong/pwbe/adoption/presentation/controller/AdoptionUpdateController.java
  src/main/java/kr/co/pawong/pwbe/adoption/presentation/controller/dto/response/AdoptionDetailResponse.java
  src/main/java/kr/co/pawong/pwbe/adoption/presentation/port/AdoptionQueryService.java
  src/main/java/kr/co/pawong/pwbe/shelter/application/service/ShelterQueryServiceImpl.java
  src/main/java/kr/co/pawong/pwbe/shelter/application/service/port/ShelterQueryRepository.java
  src/main/java/kr/co/pawong/pwbe/shelter/infrastructure/adapter/ShelterDetailAdapter.java
  src/main/java/kr/co/pawong/pwbe/shelter/infrastructure/adapter/ShelterInfoAdapter.java
  src/main/java/kr/co/pawong/pwbe/shelter/infrastructure/repository/ShelterJpaRepository.java
  src/main/java/kr/co/pawong/pwbe/shelter/infrastructure/repository/ShelterQueryRepositoryImpl.java
  src/main/java/kr/co/pawong/pwbe/shelter/infrastructure/repository/entity/ShelterEntity.java
  src/main/java/kr/co/pawong/pwbe/shelter/presentation/controller/ShelterUpdateController.java
  src/main/java/kr/co/pawong/pwbe/shelter/presentation/controller/dto/ShelterDetailDto.java
  src/main/java/kr/co/pawong/pwbe/shelter/presentation/controller/dto/ShelterInfoDto.java
  src/main/java/kr/co/pawong/pwbe/shelter/presentation/port/ShelterQueryService.java
  src/main/java/kr/co/pawong/pwbe/user/application/service/port/AdoptionInfo.java
  src/main/java/kr/co/pawong/pwbe/user/infrastructure/adapter/UserAdapter.java
  src/main/java/kr/co/pawong/pwbe/user/presentation/controller/dto/response/UserResponse.java
Labels: 🔨 Refactor, ✨ Feature

#44 [PW-39] 검색시 태그 매칭 추가
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/AdoptionAiServiceImpl.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/AdoptionSearchServiceImpl.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/dto/request/AdoptionEsDto.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/dto/request/AdoptionSearchCondition.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/support/AdoptionQueryBuilder.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/support/AdoptionSearchMapper.java
  src/main/java/kr/co/pawong/pwbe/adoption/infrastructure/repository/document/AdoptionDocument.java
Labels: 🔨 Refactor, ✨ Feature

#48 [PW-39] AI 기능 테스트 코드 수정
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/AdoptionAiServiceImpl.java
  src/main/java/kr/co/pawong/pwbe/adoption/application/service/dto/request/AdoptionEsDto.java
  src/test/java/kr/co/pawong/pwbe/adoption/application/service/AdoptionAiServiceImplTest.java
Labels: ✅ Test
